amikos-tech/chroma-go

.github/workflows/go.yml

fix: Fixed strategy matrix for chroma server testing

---

.github/workflows/lint.yaml

feat: Lint workflow as part of PR checks

---

.github/workflows/go.yml

- Removed failure in wait action (Heartbeat will fail if service is not up)
- Added pod listing in hearbeat for debugging

K8s pipeline changes

---

.github/workflows/go.yml

Updating CI Chroma and k8s versions

---

README.md
docs/docs/embeddings.md
docs/mkdocs.yml
go.mod
go.sum
ollama/ollama.go
ollama/ollama_test.go
ollama/option.go

feat: Ollama embedding function

---

Makefile
cohere/cohere_test.go
collection/collection_test.go
hf/hf_test.go
metadata/metadata_test.go
ollama/ollama_test.go
openai/client_test.go
test/chroma_client_test.go
test/test_utils.go
types/record_test.go
types/types_test.go
where/where_test.go
where_document/wheredoc_test.go

Added test build tags to all test files and test make target

test: test tagging

---

.github/workflows/go.yml
embeddings/cloudflare/cloudflare.go
embeddings/cloudflare/cloudflare_test.go
embeddings/cloudflare/option.go

feat: Cloudflare Workers AI EF

---

.github/workflows/go.yml
README.md
docs/docs/embeddings.md
pkg/embeddings/together/option.go
pkg/embeddings/together/together.go
pkg/embeddings/together/together_test.go

feat: Together AI Embeddings Support
docs: Updated docs
docs: Fixed an error in example

feat: Together AI Embeddings Support

---

docs/docs/embeddings.md
openai/openai.go
openai/openai_test.go
openai/options.go

feat: OpenAI EF Improvements

---

.github/workflows/go.yml
pkg/embeddings/mistral/mistral.go
pkg/embeddings/mistral/mistral_test.go
pkg/embeddings/mistral/option.go

feat: MistralAI embedding function

---

README.md

docs: Fix links and version support

---

.github/workflows/go.yml

chore: add 0.5.x to test matrix

---

chroma.go
test/chroma_client_test.go

fix: embedding function check before query

---

hf/hf_test.go

fix: Fixing HFEI image arch under arm

---

.github/workflows/mkdocs.yml

fix: Copying CNAME in site

---

chroma.go
test/chroma_client_test.go

feat: Adding original query inputs to query results

---

chroma.go
docs/docs/rerankers.md
pkg/rerankings/reranking.go
pkg/rerankings/reranking_test.go
test/chroma_client_test.go

feat: Reranking functions

---

.github/workflows/go.yml

chore: bump CI to use latest version

---

chroma.go
test/chroma_client_test.go

fix: basePath validation

---

README.md
chroma.go
docs/docs/client.md
test/chroma_client_test.go
test/test_utils.go

feat: Support Insecure transport, custom PKI certs and custom HTTP client

---

README.md
chroma.go
docs/docs/auth.md
docs/docs/client.md
docs/docs/filtering.md
docs/docs/index.md
test/chroma_client_test.go

feat: Making basePath an option with a default

---

README.md
docs/docs/embeddings.md

docs: Mistral AI

---

.github/workflows/nightly.yml
test/chroma_client_test.go

feat: Nightly tests against latest Chroma

---

.github/workflows/go.yml

fix: Remove go-version

---

docs/docs/embeddings.md
pkg/embeddings/voyage/option.go
pkg/embeddings/voyage/voyage.go
pkg/embeddings/voyage/voyage_test.go

Closes #128
- Also makes the Voyage AI API token a const

fix: Fixed API key refs in comments

---

.github/workflows/go.yml
.github/workflows/nightly.yml
README.md
docs/docs/embeddings.md
pkg/embeddings/nomic/nomic.go
pkg/embeddings/nomic/nomic_test.go
pkg/embeddings/nomic/option.go

feat: Nomic AI Embedding Function
chore: Updated CI
Closes #116

feat: Nomic AI Embedding Function

---

pkg/rerankings/cohere/cohere.go
pkg/rerankings/cohere/cohere_test.go
pkg/rerankings/cohere/option.go
pkg/rerankings/reranking_test.go

feat: Cohere Reranking Function

---

Makefile
pkg/commons/cohere/cohere_commons.go
pkg/commons/http/retry.go
pkg/commons/http/retry_test.go
pkg/commons/http/strategy.go

feat: Retry strategy

---

.github/workflows/go.yml

feat: Adding 0.5.5 to test matrix

---

Makefile
pkg/commons/cohere/cohere_commons.go
pkg/rerankings/cohere/cohere.go
pkg/rerankings/cohere/cohere_test.go

- Uses default client in Cohere common client
- Makes default retry backoffs exponential
- Adds rf tag to cohere reranking function

feat: Improving reranking with body closer and additional logging on error

---

.github/workflows/go.yml
Makefile
collection/collection_test.go
metadata/metadata_test.go
pkg/commons/cohere/cohere_commons_test.go
pkg/commons/http/retry_test.go
pkg/embeddings/cloudflare/cloudflare_test.go
pkg/embeddings/cohere/cohere_test.go
pkg/embeddings/gemini/gemini_test.go
pkg/embeddings/hf/hf_test.go
pkg/embeddings/mistral/mistral_test.go
pkg/embeddings/nomic/nomic_test.go
pkg/embeddings/ollama/ollama_test.go
pkg/embeddings/openai/openai_test.go
pkg/embeddings/together/together_test.go
pkg/embeddings/voyage/voyage_test.go
test/chroma_client_test.go
test/test_utils.go
types/record_test.go
types/types_test.go
where/where_test.go
where_document/wheredoc_test.go

feat: Test tagging

---

CODEOWNERS

feat: CODEOWNERS

---

go.mod
go.sum
pkg/commons/cohere/cohere_commons.go
pkg/embeddings/default_ef/constants.go
pkg/embeddings/default_ef/default_ef.go
pkg/embeddings/default_ef/default_ef_test.go
pkg/embeddings/default_ef/download_utils.go
pkg/embeddings/default_ef/download_utils_test.go
pkg/embeddings/default_ef/tensors_utils.go
pkg/tokenizers/libtokenizers/tokenizer.go
pkg/tokenizers/libtokenizers/tokenizers.h

feat: Default embedding function

---

pkg/embeddings/default_ef/constants.go
pkg/embeddings/default_ef/download_utils.go
pkg/tokenizers/libtokenizers/tokenizer.go

chore: minor default EF fixes and improvements
chore: Updating constants

chore: minor default EF fixes and improvements

---

.github/workflows/go.yml
README.md
docs/docs/embeddings.md
docs/docs/index.md
pkg/commons/http/constants.go
pkg/embeddings/jina/jina.go
pkg/embeddings/jina/jina_test.go
pkg/embeddings/jina/option.go
types/types.go

feat: Jina AI Embeddings

---

README.md
docs/docs/rerankers.md
pkg/rerankings/jina/jina.go
pkg/rerankings/jina/jina_test.go
pkg/rerankings/jina/option.go
types/types.go

feat: Jina AI Reranker

---

.github/workflows/go.yml
.gitignore
README.md
docs/docs/rerankers.md
pkg/rerankings/hf/huggingface.go
pkg/rerankings/hf/huggingface_test.go
pkg/rerankings/hf/option.go

feat: HFEI Rerankers

---

.github/workflows/go.yml
test/chroma_client_test.go

fix: Delete no longer returns IDs (0.5.12+)

---

README.md

docs: Added note about the latest changes and how to get the latest main version

---

README.md
chroma.go
docs/docs/client.md
docs/docs/embeddings.md
pkg/embeddings/default_ef/default_ef.go
pkg/embeddings/default_ef/default_ef_test.go
test/chroma_client_test.go

feat: Client close and default EF close

---

README.md
chroma.go
docs/docs/embeddings.md
pkg/embeddings/default_ef/default_ef.go
pkg/embeddings/default_ef/default_ef_test.go
test/chroma_client_test.go

feat: Use default function by default

---

chroma.go
test/chroma_client_test.go

Allows configuring the timeout for the context. Fallback is set to the default timeout (10 seconds).

Added timeout functionality

---

.github/workflows/go.yml
chroma.go
test/chroma_client_test.go

fix: Fixing queries with empty dict

---

chroma.go
pkg/commons/http/errors.go
pkg/commons/http/utils.go
test/chroma_api_test.go
test/chroma_client_test.go
test/test_utils.go

feat: API errors that make sense

---

.github/workflows/go.yml
.github/workflows/nightly.yml

fix: nightly tests against latest

---

.github/workflows/go.yml
pkg/api/v2/client_http_integration_test.go
pkg/api/v2/collection.go
pkg/api/v2/collection_http_integration_test.go
pkg/api/v2/document.go
pkg/api/v2/results.go

Closes #201
Making some quality of life improvements to stringifying results

feat: Query with IDs

---

Makefile

feat: Gotestsum

---

.github/workflows/go.yml
pkg/api/v2/client.go
pkg/api/v2/client_http.go
pkg/api/v2/client_http_integration_test.go
pkg/api/v2/collection.go
pkg/api/v2/collection_http.go
pkg/api/v2/collection_http_integration_test.go
pkg/api/v2/collection_http_test.go
pkg/api/v2/where.go

feat: Negative tests and debug print errors

---

pkg/api/v2/where_document.go
pkg/api/v2/where_document_test.go

feat: Regex support for where_document

---

README.md
pkg/api/v2/client_cloud_test.go
pkg/api/v2/collection.go
pkg/api/v2/collection_http.go
pkg/embeddings/default_ef/default_ef.go
pkg/embeddings/default_ef/download_utils.go
pkg/embeddings/default_ef/download_utils_test.go
pkg/embeddings/together/together.go
pkg/embeddings/together/together_test.go

feat: Collection forking support

---

Makefile

chore: Making cloud test cases -p=1 to avoid env var flakiness
